name: Update Mars Weather

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Update Mars weather data
      run: node update_weather.js

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "noreply@github.com"
        git add public/mars_weather.json
        git commit -m "Update Mars weather data"
        git push
